[default]
extend-ignore-words-re = ["[(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{40})]"]

[default.extend-identifiers]
# These are all from a postgres query
alo_m = "alo_m"
alo_d = "alo_d"
alo_o = "alo_o"


[files]
extend-exclude = ["_typos.toml"]