--
-- PostgreSQL database dump
--
-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2
SET
	statement_timeout = 0;

SET
	lock_timeout = 0;

SET
	idle_in_transaction_session_timeout = 0;

SET
	client_encoding = 'UTF8';

SET
	standard_conforming_strings = on;

SELECT
	pg_catalog.set_config('search_path', '', false);

SET
	check_function_bodies = false;

SET
	xmloption = content;

SET
	client_min_messages = warning;

SET
	row_security = off;

SET
	default_tablespace = '';

SET
	default_table_access_method = heap;

--
-- Name: aircraft; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft (
	aircraft_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	aircraft_icao_type_id bigint,
	aircraft_manufacturer_id bigint,
	aircraft_mode_s_id bigint NOT NULL,
	aircraft_operator_flag_code_id bigint,
	aircraft_photo_id bigint,
	aircraft_registered_owner_id bigint,
	aircraft_registration_country_prefix_id bigint,
	aircraft_registration_id bigint,
	aircraft_serial_number_id bigint,
	aircraft_type_id bigint,
	country_id bigint NOT NULL
);

ALTER TABLE
	public.aircraft OWNER TO jack;

--
-- Name: aircraft_aircraft_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft
ALTER COLUMN
	aircraft_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_aircraft_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_icao_type; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_icao_type (
	aircraft_icao_type_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	icao_type text NOT NULL
);

ALTER TABLE
	public.aircraft_icao_type OWNER TO jack;

--
-- Name: aircraft_icao_type_aircraft_icao_type_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_icao_type
ALTER COLUMN
	aircraft_icao_type_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_icao_type_aircraft_icao_type_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_manufacturer; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_manufacturer (
	aircraft_manufacturer_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	manufacturer text NOT NULL
);

ALTER TABLE
	public.aircraft_manufacturer OWNER TO jack;

--
-- Name: aircraft_manufacturer_aircraft_manufacturer_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_manufacturer
ALTER COLUMN
	aircraft_manufacturer_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_manufacturer_aircraft_manufacturer_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_mode_s; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_mode_s (
	aircraft_mode_s_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	mode_s text NOT NULL,
	CONSTRAINT aircraft_mode_s_mode_s_check CHECK ((mode_s ~ '^[A-F0-9]{6}$' :: text))
);

ALTER TABLE
	public.aircraft_mode_s OWNER TO jack;

--
-- Name: aircraft_mode_s_aircraft_mode_s_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_mode_s
ALTER COLUMN
	aircraft_mode_s_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_mode_s_aircraft_mode_s_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_operator_flag_code; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_operator_flag_code (
	aircraft_operator_flag_code_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	operator_flag_code text NOT NULL
);

ALTER TABLE
	public.aircraft_operator_flag_code OWNER TO jack;

--
-- Name: aircraft_operator_flag_code_aircraft_operator_flag_code_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_operator_flag_code
ALTER COLUMN
	aircraft_operator_flag_code_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_operator_flag_code_aircraft_operator_flag_code_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_photo; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_photo (
	aircraft_photo_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	url_photo text NOT NULL
);

ALTER TABLE
	public.aircraft_photo OWNER TO jack;

--
-- Name: aircraft_photo_aircraft_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_photo
ALTER COLUMN
	aircraft_photo_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_photo_aircraft_photo_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_registered_owner; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_registered_owner (
	aircraft_registered_owner_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	registered_owner text NOT NULL
);

ALTER TABLE
	public.aircraft_registered_owner OWNER TO jack;

--
-- Name: aircraft_registered_owner_aircraft_registered_owner_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_registered_owner
ALTER COLUMN
	aircraft_registered_owner_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_registered_owner_aircraft_registered_owner_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_registration; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_registration (
	aircraft_registration_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	registration text NOT NULL
);

ALTER TABLE
	public.aircraft_registration OWNER TO jack;

--
-- Name: aircraft_registration_aircraft_registration_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_registration
ALTER COLUMN
	aircraft_registration_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_registration_aircraft_registration_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_registration_country_prefix; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_registration_country_prefix (
	aircraft_registration_country_prefix_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	registration_country_prefix text NOT NULL
);

ALTER TABLE
	public.aircraft_registration_country_prefix OWNER TO jack;

--
-- Name: aircraft_registration_country_aircraft_registration_country_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_registration_country_prefix
ALTER COLUMN
	aircraft_registration_country_prefix_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_registration_country_aircraft_registration_country_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_serial_number; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_serial_number (
	aircraft_serial_number_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	serial_number text NOT NULL
);

ALTER TABLE
	public.aircraft_serial_number OWNER TO jack;

--
-- Name: aircraft_serial_number_aircraft_serial_number_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_serial_number
ALTER COLUMN
	aircraft_serial_number_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_serial_number_aircraft_serial_number_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_type; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.aircraft_type (
	aircraft_type_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	type text NOT NULL
);

ALTER TABLE
	public.aircraft_type OWNER TO jack;

--
-- Name: aircraft_type_aircraft_type_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.aircraft_type
ALTER COLUMN
	aircraft_type_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.aircraft_type_aircraft_type_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airline; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airline (
	airline_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	airline_name text NOT NULL,
	airline_callsign text,
	country_id bigint NOT NULL,
	iata_prefix text,
	icao_prefix text NOT NULL,
	CONSTRAINT airline_iata_prefix_check CHECK ((iata_prefix ~ '^[A-Z0-9]{2}$' :: text)),
	CONSTRAINT airline_icao_prefix_check CHECK ((icao_prefix ~ '^[A-Z]{3}$' :: text))
);

ALTER TABLE
	public.airline OWNER TO jack;

--
-- Name: airline_airline_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airline
ALTER COLUMN
	airline_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airline_airline_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport (
	airport_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	airport_elevation_id bigint,
	airport_iata_code_id bigint,
	airport_icao_code_id bigint,
	airport_latitude_id bigint,
	airport_longitude_id bigint,
	airport_municipality_id bigint,
	airport_name_id bigint NOT NULL,
	airport_type_id bigint NOT NULL,
	country_id bigint NOT NULL
);

ALTER TABLE
	public.airport OWNER TO jack;

--
-- Name: airport_airport_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport
ALTER COLUMN
	airport_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_airport_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_elevation; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_elevation (
	airport_elevation_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	elevation integer
);

ALTER TABLE
	public.airport_elevation OWNER TO jack;

--
-- Name: airport_elevation_airport_elevation_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_elevation
ALTER COLUMN
	airport_elevation_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_elevation_airport_elevation_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_iata_code; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_iata_code (
	airport_iata_code_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	iata_code text NOT NULL,
	CONSTRAINT airport_iata_code_iata_code_check CHECK ((iata_code ~ '^[A-Z0-9]{3}$' :: text))
);

ALTER TABLE
	public.airport_iata_code OWNER TO jack;

--
-- Name: airport_iata_code_airport_iata_code_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_iata_code
ALTER COLUMN
	airport_iata_code_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_iata_code_airport_iata_code_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_icao_code; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_icao_code (
	airport_icao_code_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	icao_code text NOT NULL,
	CONSTRAINT airport_icao_code_icao_code_check CHECK ((icao_code ~ '^[A-Z0-9]{3,4}$' :: text))
);

ALTER TABLE
	public.airport_icao_code OWNER TO jack;

--
-- Name: airport_icao_code_airport_icao_code_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_icao_code
ALTER COLUMN
	airport_icao_code_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_icao_code_airport_icao_code_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_latitude; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_latitude (
	airport_latitude_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	latitude double precision
);

ALTER TABLE
	public.airport_latitude OWNER TO jack;

--
-- Name: airport_latitude_airport_latitude_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_latitude
ALTER COLUMN
	airport_latitude_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_latitude_airport_latitude_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_longitude; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_longitude (
	airport_longitude_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	longitude double precision
);

ALTER TABLE
	public.airport_longitude OWNER TO jack;

--
-- Name: airport_longitude_airport_longitude_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_longitude
ALTER COLUMN
	airport_longitude_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_longitude_airport_longitude_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_municipality; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_municipality (
	airport_municipality_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	municipality text
);

ALTER TABLE
	public.airport_municipality OWNER TO jack;

--
-- Name: airport_municipality_airport_municipality_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_municipality
ALTER COLUMN
	airport_municipality_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_municipality_airport_municipality_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_name; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_name (
	airport_name_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	name text
);

ALTER TABLE
	public.airport_name OWNER TO jack;

--
-- Name: airport_name_airport_name_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_name
ALTER COLUMN
	airport_name_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_name_airport_name_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: airport_type; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.airport_type (
	airport_type_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	type text
);

ALTER TABLE
	public.airport_type OWNER TO jack;

--
-- Name: airport_type_airport_type_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.airport_type
ALTER COLUMN
	airport_type_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.airport_type_airport_type_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: country; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.country (
	country_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	country_name text NOT NULL,
	country_iso_name text NOT NULL,
	CONSTRAINT country_country_iso_name_check CHECK ((country_iso_name ~ '^[A-Z]{2,3}$' :: text))
);

ALTER TABLE
	public.country OWNER TO jack;

--
-- Name: country_country_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.country
ALTER COLUMN
	country_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.country_country_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: error_log; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.error_log (
	error_log_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	http_code smallint,
	level text NOT NULL,
	message text,
	stack text,
	uuid text,
	CONSTRAINT error_log_level_check CHECK (
		(
			level = ANY (
				ARRAY ['warn'::text, 'error'::text, 'verbose'::text, 'info'::text, 'debug'::text]
			)
		)
	)
);

ALTER TABLE
	public.error_log OWNER TO jack;

--
-- Name: error_log_error_log_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.error_log
ALTER COLUMN
	error_log_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.error_log_error_log_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: flightroute; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.flightroute (
	flightroute_id bigint NOT NULL,
	airport_origin_id bigint NOT NULL,
	airport_midpoint_id bigint,
	airport_destination_id bigint NOT NULL,
	flightroute_callsign_id bigint NOT NULL
);

ALTER TABLE
	public.flightroute OWNER TO jack;

--
-- Name: flightroute_callsign; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.flightroute_callsign (
	flightroute_callsign_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	airline_id bigint,
	iata_prefix_id bigint,
	icao_prefix_id bigint,
	callsign_id bigint
);

ALTER TABLE
	public.flightroute_callsign OWNER TO jack;

--
-- Name: flightroute_callsign_flightroute_callsign_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.flightroute_callsign
ALTER COLUMN
	flightroute_callsign_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.flightroute_callsign_flightroute_callsign_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: flightroute_callsign_inner; Type: TABLE; Schema: public; Owner: jack
--
CREATE TABLE public.flightroute_callsign_inner (
	flightroute_callsign_inner_id bigint NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	callsign text NOT NULL
);

ALTER TABLE
	public.flightroute_callsign_inner OWNER TO jack;

--
-- Name: flightroute_callsign_inner_flightroute_callsign_inner_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.flightroute_callsign_inner
ALTER COLUMN
	flightroute_callsign_inner_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.flightroute_callsign_inner_flightroute_callsign_inner_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: flightroute_flightroute_id_seq; Type: SEQUENCE; Schema: public; Owner: jack
--
ALTER TABLE
	public.flightroute
ALTER COLUMN
	flightroute_id
ADD
	GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.flightroute_flightroute_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
	);

--
-- Name: aircraft_icao_type aircraft_icao_type_icao_type_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_icao_type
ADD
	CONSTRAINT aircraft_icao_type_icao_type_key UNIQUE (icao_type);

--
-- Name: aircraft_icao_type aircraft_icao_type_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_icao_type
ADD
	CONSTRAINT aircraft_icao_type_pkey PRIMARY KEY (aircraft_icao_type_id);

--
-- Name: aircraft_manufacturer aircraft_manufacturer_manufacturer_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_manufacturer
ADD
	CONSTRAINT aircraft_manufacturer_manufacturer_key UNIQUE (manufacturer);

--
-- Name: aircraft_manufacturer aircraft_manufacturer_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_manufacturer
ADD
	CONSTRAINT aircraft_manufacturer_pkey PRIMARY KEY (aircraft_manufacturer_id);

--
-- Name: aircraft_mode_s aircraft_mode_s_mode_s_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_mode_s
ADD
	CONSTRAINT aircraft_mode_s_mode_s_key UNIQUE (mode_s);

--
-- Name: aircraft_mode_s aircraft_mode_s_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_mode_s
ADD
	CONSTRAINT aircraft_mode_s_pkey PRIMARY KEY (aircraft_mode_s_id);

--
-- Name: aircraft_operator_flag_code aircraft_operator_flag_code_operator_flag_code_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_operator_flag_code
ADD
	CONSTRAINT aircraft_operator_flag_code_operator_flag_code_key UNIQUE (operator_flag_code);

--
-- Name: aircraft_operator_flag_code aircraft_operator_flag_code_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_operator_flag_code
ADD
	CONSTRAINT aircraft_operator_flag_code_pkey PRIMARY KEY (aircraft_operator_flag_code_id);

--
-- Name: aircraft_photo aircraft_photo_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_photo
ADD
	CONSTRAINT aircraft_photo_pkey PRIMARY KEY (aircraft_photo_id);

--
-- Name: aircraft_photo aircraft_photo_url_photo_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_photo
ADD
	CONSTRAINT aircraft_photo_url_photo_key UNIQUE (url_photo);

--
-- Name: aircraft aircraft_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_pkey PRIMARY KEY (aircraft_id);

--
-- Name: aircraft_registered_owner aircraft_registered_owner_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registered_owner
ADD
	CONSTRAINT aircraft_registered_owner_pkey PRIMARY KEY (aircraft_registered_owner_id);

--
-- Name: aircraft_registered_owner aircraft_registered_owner_registered_owner_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registered_owner
ADD
	CONSTRAINT aircraft_registered_owner_registered_owner_key UNIQUE (registered_owner);

--
-- Name: aircraft_registration_country_prefix aircraft_registration_country_p_registration_country_prefix_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registration_country_prefix
ADD
	CONSTRAINT aircraft_registration_country_p_registration_country_prefix_key UNIQUE (registration_country_prefix);

--
-- Name: aircraft_registration_country_prefix aircraft_registration_country_prefix_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registration_country_prefix
ADD
	CONSTRAINT aircraft_registration_country_prefix_pkey PRIMARY KEY (aircraft_registration_country_prefix_id);

--
-- Name: aircraft_registration aircraft_registration_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registration
ADD
	CONSTRAINT aircraft_registration_pkey PRIMARY KEY (aircraft_registration_id);

--
-- Name: aircraft_registration aircraft_registration_registration_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_registration
ADD
	CONSTRAINT aircraft_registration_registration_key UNIQUE (registration);

--
-- Name: aircraft_serial_number aircraft_serial_number_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_serial_number
ADD
	CONSTRAINT aircraft_serial_number_pkey PRIMARY KEY (aircraft_serial_number_id);

--
-- Name: aircraft_serial_number aircraft_serial_number_serial_number_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_serial_number
ADD
	CONSTRAINT aircraft_serial_number_serial_number_key UNIQUE (serial_number);

--
-- Name: aircraft_type aircraft_type_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_type
ADD
	CONSTRAINT aircraft_type_pkey PRIMARY KEY (aircraft_type_id);

--
-- Name: aircraft_type aircraft_type_type_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft_type
ADD
	CONSTRAINT aircraft_type_type_key UNIQUE (type);

--
-- Name: airline airline_icao_prefix_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airline
ADD
	CONSTRAINT airline_icao_prefix_key UNIQUE (icao_prefix);

--
-- Name: airline airline_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airline
ADD
	CONSTRAINT airline_pkey PRIMARY KEY (airline_id);

--
-- Name: airport_elevation airport_elevation_elevation_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_elevation
ADD
	CONSTRAINT airport_elevation_elevation_key UNIQUE (elevation);

--
-- Name: airport_elevation airport_elevation_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_elevation
ADD
	CONSTRAINT airport_elevation_pkey PRIMARY KEY (airport_elevation_id);

--
-- Name: airport_iata_code airport_iata_code_iata_code_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_iata_code
ADD
	CONSTRAINT airport_iata_code_iata_code_key UNIQUE (iata_code);

--
-- Name: airport_iata_code airport_iata_code_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_iata_code
ADD
	CONSTRAINT airport_iata_code_pkey PRIMARY KEY (airport_iata_code_id);

--
-- Name: airport_icao_code airport_icao_code_icao_code_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_icao_code
ADD
	CONSTRAINT airport_icao_code_icao_code_key UNIQUE (icao_code);

--
-- Name: airport_icao_code airport_icao_code_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_icao_code
ADD
	CONSTRAINT airport_icao_code_pkey PRIMARY KEY (airport_icao_code_id);

--
-- Name: airport_latitude airport_latitude_latitude_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_latitude
ADD
	CONSTRAINT airport_latitude_latitude_key UNIQUE (latitude);

--
-- Name: airport_latitude airport_latitude_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_latitude
ADD
	CONSTRAINT airport_latitude_pkey PRIMARY KEY (airport_latitude_id);

--
-- Name: airport_longitude airport_longitude_longitude_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_longitude
ADD
	CONSTRAINT airport_longitude_longitude_key UNIQUE (longitude);

--
-- Name: airport_longitude airport_longitude_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_longitude
ADD
	CONSTRAINT airport_longitude_pkey PRIMARY KEY (airport_longitude_id);

--
-- Name: airport_municipality airport_municipality_municipality_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_municipality
ADD
	CONSTRAINT airport_municipality_municipality_key UNIQUE (municipality);

--
-- Name: airport_municipality airport_municipality_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_municipality
ADD
	CONSTRAINT airport_municipality_pkey PRIMARY KEY (airport_municipality_id);

--
-- Name: airport_name airport_name_name_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_name
ADD
	CONSTRAINT airport_name_name_key UNIQUE (name);

--
-- Name: airport_name airport_name_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_name
ADD
	CONSTRAINT airport_name_pkey PRIMARY KEY (airport_name_id);

--
-- Name: airport airport_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_pkey PRIMARY KEY (airport_id);

--
-- Name: airport_type airport_type_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_type
ADD
	CONSTRAINT airport_type_pkey PRIMARY KEY (airport_type_id);

--
-- Name: airport_type airport_type_type_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport_type
ADD
	CONSTRAINT airport_type_type_key UNIQUE (type);

--
-- Name: country country_country_iso_name_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.country
ADD
	CONSTRAINT country_country_iso_name_key UNIQUE (country_iso_name);

--
-- Name: country country_country_name_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.country
ADD
	CONSTRAINT country_country_name_key UNIQUE (country_name);

--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.country
ADD
	CONSTRAINT country_pkey PRIMARY KEY (country_id);

--
-- Name: error_log error_log_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.error_log
ADD
	CONSTRAINT error_log_pkey PRIMARY KEY (error_log_id);

--
-- Name: flightroute_callsign_inner flightroute_callsign_inner_callsign_key; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign_inner
ADD
	CONSTRAINT flightroute_callsign_inner_callsign_key UNIQUE (callsign);

--
-- Name: flightroute_callsign_inner flightroute_callsign_inner_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign_inner
ADD
	CONSTRAINT flightroute_callsign_inner_pkey PRIMARY KEY (flightroute_callsign_inner_id);

--
-- Name: flightroute_callsign flightroute_callsign_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign
ADD
	CONSTRAINT flightroute_callsign_pkey PRIMARY KEY (flightroute_callsign_id);

--
-- Name: flightroute flightroute_pkey; Type: CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute
ADD
	CONSTRAINT flightroute_pkey PRIMARY KEY (flightroute_id);

--
-- Name: aircraft_mode_s_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX aircraft_mode_s_index ON public.aircraft_mode_s USING btree (mode_s);

--
-- Name: aircraft_registration_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX aircraft_registration_index ON public.aircraft_registration USING btree (registration);

--
-- Name: aircraft_type_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX aircraft_type_index ON public.aircraft_type USING btree (type);

--
-- Name: airline_iata_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airline_iata_index ON public.airline USING btree (iata_prefix);

--
-- Name: airline_icao_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airline_icao_index ON public.airline USING btree (icao_prefix);

--
-- Name: airline_name_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airline_name_index ON public.airline USING btree (airline_name);

--
-- Name: airport_iata_code_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_iata_code_index ON public.airport_iata_code USING btree (iata_code);

--
-- Name: airport_icao_code_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_icao_code_index ON public.airport_icao_code USING btree (icao_code);

--
-- Name: airport_latitude_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_latitude_index ON public.airport_latitude USING btree (latitude);

--
-- Name: airport_longitude_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_longitude_index ON public.airport_longitude USING btree (longitude);

--
-- Name: airport_municipality_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_municipality_index ON public.airport_municipality USING btree (municipality);

--
-- Name: airport_name_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_name_index ON public.airport_name USING btree (name);

--
-- Name: airport_type_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX airport_type_index ON public.airport_type USING btree (type);

--
-- Name: country_iso_name_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX country_iso_name_index ON public.country USING btree (country_iso_name);

--
-- Name: country_name_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX country_name_index ON public.country USING btree (country_name);

--
-- Name: icao_type_index; Type: INDEX; Schema: public; Owner: jack
--
CREATE INDEX icao_type_index ON public.aircraft_icao_type USING btree (icao_type);

--
-- Name: aircraft aircraft_aircraft_icao_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_icao_type_id_fkey FOREIGN KEY (aircraft_icao_type_id) REFERENCES public.aircraft_icao_type(aircraft_icao_type_id);

--
-- Name: aircraft aircraft_aircraft_manufacturer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_manufacturer_id_fkey FOREIGN KEY (aircraft_manufacturer_id) REFERENCES public.aircraft_manufacturer(aircraft_manufacturer_id);

--
-- Name: aircraft aircraft_aircraft_mode_s_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_mode_s_id_fkey FOREIGN KEY (aircraft_mode_s_id) REFERENCES public.aircraft_mode_s(aircraft_mode_s_id);

--
-- Name: aircraft aircraft_aircraft_operator_flag_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_operator_flag_code_id_fkey FOREIGN KEY (aircraft_operator_flag_code_id) REFERENCES public.aircraft_operator_flag_code(aircraft_operator_flag_code_id);

--
-- Name: aircraft aircraft_aircraft_photo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_photo_id_fkey FOREIGN KEY (aircraft_photo_id) REFERENCES public.aircraft_photo(aircraft_photo_id);

--
-- Name: aircraft aircraft_aircraft_registered_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_registered_owner_id_fkey FOREIGN KEY (aircraft_registered_owner_id) REFERENCES public.aircraft_registered_owner(aircraft_registered_owner_id);

--
-- Name: aircraft aircraft_aircraft_registration_country_prefix_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_registration_country_prefix_id_fkey FOREIGN KEY (aircraft_registration_country_prefix_id) REFERENCES public.aircraft_registration_country_prefix(aircraft_registration_country_prefix_id);

--
-- Name: aircraft aircraft_aircraft_registration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_registration_id_fkey FOREIGN KEY (aircraft_registration_id) REFERENCES public.aircraft_registration(aircraft_registration_id);

--
-- Name: aircraft aircraft_aircraft_serial_number_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_serial_number_id_fkey FOREIGN KEY (aircraft_serial_number_id) REFERENCES public.aircraft_serial_number(aircraft_serial_number_id);

--
-- Name: aircraft aircraft_aircraft_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_aircraft_type_id_fkey FOREIGN KEY (aircraft_type_id) REFERENCES public.aircraft_type(aircraft_type_id);

--
-- Name: aircraft aircraft_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.aircraft
ADD
	CONSTRAINT aircraft_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country(country_id);

--
-- Name: airline airline_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airline
ADD
	CONSTRAINT airline_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country(country_id);

--
-- Name: airport airport_airport_elevation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_elevation_id_fkey FOREIGN KEY (airport_elevation_id) REFERENCES public.airport_elevation(airport_elevation_id);

--
-- Name: airport airport_airport_iata_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_iata_code_id_fkey FOREIGN KEY (airport_iata_code_id) REFERENCES public.airport_iata_code(airport_iata_code_id);

--
-- Name: airport airport_airport_icao_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_icao_code_id_fkey FOREIGN KEY (airport_icao_code_id) REFERENCES public.airport_icao_code(airport_icao_code_id);

--
-- Name: airport airport_airport_latitude_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_latitude_id_fkey FOREIGN KEY (airport_latitude_id) REFERENCES public.airport_latitude(airport_latitude_id);

--
-- Name: airport airport_airport_longitude_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_longitude_id_fkey FOREIGN KEY (airport_longitude_id) REFERENCES public.airport_longitude(airport_longitude_id);

--
-- Name: airport airport_airport_municipality_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_municipality_id_fkey FOREIGN KEY (airport_municipality_id) REFERENCES public.airport_municipality(airport_municipality_id);

--
-- Name: airport airport_airport_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_name_id_fkey FOREIGN KEY (airport_name_id) REFERENCES public.airport_name(airport_name_id);

--
-- Name: airport airport_airport_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_airport_type_id_fkey FOREIGN KEY (airport_type_id) REFERENCES public.airport_type(airport_type_id);

--
-- Name: airport airport_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.airport
ADD
	CONSTRAINT airport_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country(country_id);

--
-- Name: flightroute flightroute_airport_destination_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute
ADD
	CONSTRAINT flightroute_airport_destination_id_fkey FOREIGN KEY (airport_destination_id) REFERENCES public.airport(airport_id);

--
-- Name: flightroute flightroute_airport_midpoint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute
ADD
	CONSTRAINT flightroute_airport_midpoint_id_fkey FOREIGN KEY (airport_midpoint_id) REFERENCES public.airport(airport_id);

--
-- Name: flightroute flightroute_airport_origin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute
ADD
	CONSTRAINT flightroute_airport_origin_id_fkey FOREIGN KEY (airport_origin_id) REFERENCES public.airport(airport_id);

--
-- Name: flightroute_callsign flightroute_callsign_airline_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign
ADD
	CONSTRAINT flightroute_callsign_airline_id_fkey FOREIGN KEY (airline_id) REFERENCES public.airline(airline_id);

--
-- Name: flightroute_callsign flightroute_callsign_callsign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign
ADD
	CONSTRAINT flightroute_callsign_callsign_id_fkey FOREIGN KEY (callsign_id) REFERENCES public.flightroute_callsign_inner(flightroute_callsign_inner_id);

--
-- Name: flightroute_callsign flightroute_callsign_iata_prefix_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign
ADD
	CONSTRAINT flightroute_callsign_iata_prefix_id_fkey FOREIGN KEY (iata_prefix_id) REFERENCES public.flightroute_callsign_inner(flightroute_callsign_inner_id);

--
-- Name: flightroute_callsign flightroute_callsign_icao_prefix_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute_callsign
ADD
	CONSTRAINT flightroute_callsign_icao_prefix_id_fkey FOREIGN KEY (icao_prefix_id) REFERENCES public.flightroute_callsign_inner(flightroute_callsign_inner_id);

--
-- Name: flightroute flightroute_flightroute_callsign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jack
--
ALTER TABLE
	ONLY public.flightroute
ADD
	CONSTRAINT flightroute_flightroute_callsign_id_fkey FOREIGN KEY (flightroute_callsign_id) REFERENCES public.flightroute_callsign(flightroute_callsign_id);

--
-- Name: TABLE aircraft; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft TO adsbdb;

--
-- Name: SEQUENCE aircraft_aircraft_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_aircraft_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_icao_type; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_icao_type TO adsbdb;

--
-- Name: SEQUENCE aircraft_icao_type_aircraft_icao_type_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_icao_type_aircraft_icao_type_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_manufacturer; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_manufacturer TO adsbdb;

--
-- Name: SEQUENCE aircraft_manufacturer_aircraft_manufacturer_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_manufacturer_aircraft_manufacturer_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_mode_s; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_mode_s TO adsbdb;

--
-- Name: SEQUENCE aircraft_mode_s_aircraft_mode_s_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_mode_s_aircraft_mode_s_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_operator_flag_code; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_operator_flag_code TO adsbdb;

--
-- Name: SEQUENCE aircraft_operator_flag_code_aircraft_operator_flag_code_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_operator_flag_code_aircraft_operator_flag_code_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_photo; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_photo TO adsbdb;

--
-- Name: SEQUENCE aircraft_photo_aircraft_photo_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_photo_aircraft_photo_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_registered_owner; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_registered_owner TO adsbdb;

--
-- Name: SEQUENCE aircraft_registered_owner_aircraft_registered_owner_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_registered_owner_aircraft_registered_owner_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_registration; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_registration TO adsbdb;

--
-- Name: SEQUENCE aircraft_registration_aircraft_registration_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_registration_aircraft_registration_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_registration_country_prefix; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_registration_country_prefix TO adsbdb;

--
-- Name: SEQUENCE aircraft_registration_country_aircraft_registration_country_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_registration_country_aircraft_registration_country_seq TO adsbdb;

--
-- Name: TABLE aircraft_serial_number; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_serial_number TO adsbdb;

--
-- Name: SEQUENCE aircraft_serial_number_aircraft_serial_number_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_serial_number_aircraft_serial_number_id_seq TO adsbdb;

--
-- Name: TABLE aircraft_type; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.aircraft_type TO adsbdb;

--
-- Name: SEQUENCE aircraft_type_aircraft_type_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.aircraft_type_aircraft_type_id_seq TO adsbdb;

--
-- Name: TABLE airline; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airline TO adsbdb;

--
-- Name: SEQUENCE airline_airline_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airline_airline_id_seq TO adsbdb;

--
-- Name: TABLE airport; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport TO adsbdb;

--
-- Name: SEQUENCE airport_airport_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_airport_id_seq TO adsbdb;

--
-- Name: TABLE airport_elevation; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_elevation TO adsbdb;

--
-- Name: SEQUENCE airport_elevation_airport_elevation_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_elevation_airport_elevation_id_seq TO adsbdb;

--
-- Name: TABLE airport_iata_code; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_iata_code TO adsbdb;

--
-- Name: SEQUENCE airport_iata_code_airport_iata_code_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_iata_code_airport_iata_code_id_seq TO adsbdb;

--
-- Name: TABLE airport_icao_code; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_icao_code TO adsbdb;

--
-- Name: SEQUENCE airport_icao_code_airport_icao_code_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_icao_code_airport_icao_code_id_seq TO adsbdb;

--
-- Name: TABLE airport_latitude; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_latitude TO adsbdb;

--
-- Name: SEQUENCE airport_latitude_airport_latitude_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_latitude_airport_latitude_id_seq TO adsbdb;

--
-- Name: TABLE airport_longitude; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_longitude TO adsbdb;

--
-- Name: SEQUENCE airport_longitude_airport_longitude_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_longitude_airport_longitude_id_seq TO adsbdb;

--
-- Name: TABLE airport_municipality; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_municipality TO adsbdb;

--
-- Name: SEQUENCE airport_municipality_airport_municipality_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_municipality_airport_municipality_id_seq TO adsbdb;

--
-- Name: TABLE airport_name; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_name TO adsbdb;

--
-- Name: SEQUENCE airport_name_airport_name_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_name_airport_name_id_seq TO adsbdb;

--
-- Name: TABLE airport_type; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.airport_type TO adsbdb;

--
-- Name: SEQUENCE airport_type_airport_type_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.airport_type_airport_type_id_seq TO adsbdb;

--
-- Name: TABLE country; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.country TO adsbdb;

--
-- Name: SEQUENCE country_country_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.country_country_id_seq TO adsbdb;

--
-- Name: TABLE error_log; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.error_log TO adsbdb;

--
-- Name: SEQUENCE error_log_error_log_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.error_log_error_log_id_seq TO adsbdb;

--
-- Name: TABLE flightroute; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.flightroute TO adsbdb;

--
-- Name: TABLE flightroute_callsign; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.flightroute_callsign TO adsbdb;

--
-- Name: SEQUENCE flightroute_callsign_flightroute_callsign_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.flightroute_callsign_flightroute_callsign_id_seq TO adsbdb;

--
-- Name: TABLE flightroute_callsign_inner; Type: ACL; Schema: public; Owner: jack
--
GRANT ALL ON TABLE public.flightroute_callsign_inner TO adsbdb;

--
-- Name: SEQUENCE flightroute_callsign_inner_flightroute_callsign_inner_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.flightroute_callsign_inner_flightroute_callsign_inner_id_seq TO adsbdb;

--
-- Name: SEQUENCE flightroute_flightroute_id_seq; Type: ACL; Schema: public; Owner: jack
--
GRANT
SELECT
,
	USAGE ON SEQUENCE public.flightroute_flightroute_id_seq TO adsbdb;

--
-- PostgreSQL database dump complete
--